name: Deploy Cloudflare Worker
on:
  workflow_dispatch:
    inputs:
      production_deploy:
        description: 'Deploy to production'
        required: true
        type: boolean
        default: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: pnpm run test

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          command: ${{ inputs.production_deploy && 'deploy --env production' || 'deploy' }}
